<?php

namespace PMM\CoreBundle\Repository;

/**
 * ComMedocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComMedocRepository extends \Doctrine\ORM\EntityRepository
{
}
