medicament_index:
    path:     /
    defaults: { _controller: "PMMCoreBundle:Medicament:index" }
    methods:  GET

medicament_show:
    path:     /{id}/show
    defaults: { _controller: "PMMCoreBundle:Medicament:show" }
    methods:  GET

medicament_new:
    path:     /new
    defaults: { _controller: "PMMCoreBundle:Medicament:new" }
    methods:  [GET, POST]

medicament_edit:
    path:     /{id}/edit
    defaults: { _controller: "PMMCoreBundle:Medicament:edit" }
    methods:  [GET, POST]

medicament_delete:
    path:     /{id}/delete
    defaults: { _controller: "PMMCoreBundle:Medicament:delete" }
    methods:  DELETE
