patient_index:
    path:     /
    defaults: { _controller: "PMMCoreBundle:Patient:index" }
    methods:  GET

patient_show:
    path:     /{id}/show
    defaults: { _controller: "PMMCoreBundle:Patient:show" }
    methods:  GET

patient_new:
    path:     /new
    defaults: { _controller: "PMMCoreBundle:Patient:new" }
    methods:  [GET, POST]

patient_edit:
    path:     /{id}/edit
    defaults: { _controller: "PMMCoreBundle:Patient:edit" }
    methods:  [GET, POST]

patient_delete:
    path:     /{id}/delete
    defaults: { _controller: "PMMCoreBundle:Patient:delete" }
    methods:  DELETE
